
 Importing the Dependencies

In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [2]:
# Importing the Dependencies
import numpy as np
import pandas as pd # This line imports pandas and assigns it the alias 'pd'
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# loading the dataset to a pandas Dataframe
# This line uses the 'pd' alias to call the read_csv function
credit_card_data = pd.read_csv('/creditcard.csv.zip')

In [4]:
# first 5 rows of the dataset
credit_card_data.head()

   Time        V1        V2        V3  ...       V27       V28  Amount  Class
0   0.0 -1.359807 -0.072781  2.536347  ...  0.133558 -0.021053  149.62      0
1   0.0  1.191857  0.266151  0.166480  ... -0.008983  0.014724    2.69      0
2   1.0 -1.358354 -1.340163  1.773209  ... -0.055353 -0.059752  378.66      0
3   1.0 -0.966272 -0.185226  1.792993  ...  0.062723  0.061458  123.50      0
4   2.0 -1.158233  0.877737  1.548718  ...  0.219422  0.215153   69.99      0

[5 rows x 31 columns]

In [5]:
credit_card_data.tail()

            Time         V1         V2  ...       V28  Amount  Class
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[5 rows x 31 columns]

In [6]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [8]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [9]:
# distribution of legit transaction & fraudulent transaction
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

This dataset is highly unblanced

0 --> Normal Transaction
1 --> fraudulent Transaction

In [10]:
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [11]:
# statistical measures of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [12]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [13]:
# compare the values for both transaction
credit_card_data.groupby('Class').mean()

               Time        V1        V2  ...       V27       V28      Amount
Class                                    ...
0      94838.202258  0.008258 -0.006271  ... -0.000295 -0.000131   88.291022
1      80746.806911 -4.771948  3.623778  ...  0.170575  0.075667  122.211321

[2 rows x 30 columns]

Under Sampling

Build a sample dataset containing similar distribution of normal transaction and fraudulent Transaction

Number of Fraudulent Transaction-->492

In [14]:
legit

            Time         V1         V2  ...       V28  Amount  Class
0            0.0  -1.359807  -0.072781  ... -0.021053  149.62      0
1            0.0   1.191857   0.266151  ...  0.014724    2.69      0
2            1.0  -1.358354  -1.340163  ... -0.059752  378.66      0
3            1.0  -0.966272  -0.185226  ...  0.061458  123.50      0
4            2.0  -1.158233   0.877737  ...  0.215153   69.99      0
...          ...        ...        ...  ...       ...     ...    ...
284802  172786.0 -11.881118  10.071785  ...  0.823731    0.77      0
284803  172787.0  -0.732789  -0.055080  ... -0.053527   24.79      0
284804  172788.0   1.919565  -0.301254  ... -0.026561   67.88      0
284805  172788.0  -0.240440   0.530483  ...  0.104533   10.00      0
284806  172792.0  -0.533413  -0.189733  ...  0.013649  217.00      0

[284315 rows x 31 columns]

In [15]:
legit_sample = legit.sample(n=492)

Concatenating two Dataframe

In [16]:
new_dataset = pd.concat([legit_sample, fraud], axis=0)

In [18]:
 new_dataset.head()

            Time        V1        V2  ...       V28  Amount  Class
128517   78741.0 -1.088929  1.173098  ...  0.079940   31.39      0
169165  119559.0  0.125635  1.037372  ...  0.071628    2.28      0
239107  149955.0  0.145606  1.017261  ...  0.083761    4.49      0
121424   76185.0  1.243118  0.240622  ...  0.021309   10.87      0
107700   70567.0  1.279572  0.273420  ...  0.025284    0.12      0

[5 rows x 31 columns]

In [19]:
new_dataset.tail()

            Time        V1        V2  ...       V28  Amount  Class
128517   78741.0 -1.088929  1.173098  ...  0.079940   31.39      0
169165  119559.0  0.125635  1.037372  ...  0.071628    2.28      0
239107  149955.0  0.145606  1.017261  ...  0.083761    4.49      0
121424   76185.0  1.243118  0.240622  ...  0.021309   10.87      0
107700   70567.0  1.279572  0.273420  ...  0.025284    0.12      0

[5 rows x 31 columns]

In [20]:
new_dataset['Class'].value_counts()

Class
0    5
Name: count, dtype: int64

In [21]:
new_dataset.groupby('Class').mean()

          Time     V1        V2        V3  ...      V26       V27       V28  Amount
Class                                      ...
0      99001.4  0.341  0.748355  0.210547  ...  0.00215  0.108702  0.056384    9.83

[1 rows x 30 columns]

Splitting the data into Features & Targets

In [22]:
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']

In [23]:
print(X)

            Time        V1        V2  ...       V27       V28  Amount
128517   78741.0 -1.088929  1.173098  ...  0.087893  0.079940   31.39
169165  119559.0  0.125635  1.037372  ...  0.227278  0.071628    2.28
239107  149955.0  0.145606  1.017261  ...  0.220433  0.083761    4.49
121424   76185.0  1.243118  0.240622  ... -0.029111  0.021309   10.87
107700   70567.0  1.279572  0.273420  ...  0.037018  0.025284    0.12

[5 rows x 30 columns]

In [24]:
print(Y)

128517    0
169165    0
239107    0
121424    0
107700    0
Name: Class, dtype: int64

Split the data into Training data & testing data

In [25]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [26]:
print(X.shape, X_train.shape, X_test.shape)

(5, 30) (4, 30) (1, 30)

Model Training

logistic regression

In [39]:
# Importing the Dependencies
import numpy as np
import pandas as pd # This line imports pandas and assigns it the alias 'pd'
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# loading the dataset to a pandas Dataframe
# This line uses the 'pd' alias to call the read_csv function
credit_card_data = pd.read_csv('/creditcard.csv.zip')
# %%
# first 5 rows of the dataset
credit_card_data.head()
# %%
credit_card_data.tail()
# %%
# dataset informations
credit_card_data.info()
# %%
# checking the number of missing values in each column
credit_card_data.isnull().sum()
# %%
# distribution of legit transaction & fraudulent transaction
credit_card_data['Class'].value_counts()
# %% [markdown]
# This dataset is highly unblanced
#
# %% [markdown]
# 0 --> Normal Transaction
# 1 --> fraudulent Transaction
#
# %%
# separating the data for analysis
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]
print(legit.shape)
print(fraud.shape)
# %%
# statistical measures of the data
legit.Amount.describe()
# %%
fraud.Amount.describe()
# %%
# compare the values for both transaction
credit_card_data.groupby('Class').mean()
# %% [markdown]
# Under Sampling
#
# %% [markdown]
# Build a sample dataset containing similar distribution of normal transaction and fraudulent Transaction
#
# Number of Fraudulent Transaction-->492
# %%
legit
# %%
# Increased the sample size for legitimate transactions to reduce the chance of a single-class training set
legit_sample = legit.sample(n=1000) # Increased sample size from 492 to 1000
# %% [markdown]
# Concatenating two Dataframe
# %%
new_dataset = pd.concat([legit_sample, fraud], axis=0)
# %%
new_dataset.head()
# %%
new_dataset.tail()
# %%
new_dataset['Class'].value_counts()
# %%
new_dataset.groupby('Class').mean()
# %% [markdown]
# Splitting the data into Features & Targets
# %%
X = new_dataset.drop(columns='Class', axis=1)
Y = new_dataset['Class']
# %%
print(X)
# %%
print(Y)
# %% [markdown]
# Split the data into Training data & testing data
# %%
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)
# %%
print(X.shape, X_train.shape, X_test.shape)
# %% [markdown]
# Model Training
# %% [markdown]
# logistic regression
# %%
#training the logistic regression model with traing data
model = LogisticRegression()
model.fit(X_train, Y_train)

# %% [markdown]
# model evaluation
# %% [markdown]
# Accuracy Score
# %%
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB
(284315, 31)
(492, 31)
            Time        V1        V2  ...       V27       V28  Amount
57735    48045.0  0.636301 -1.396960  ... -0.098144  0.048773  295.70
197206  131893.0 -0.598391  0.326041  ... -0.003953 -0.043369   62.00
148196   89549.0 -1.348415  0.374424  ... -0.064508 -0.067451   32.55
68761    53131.0 -1.449852 -0.750833  ... -0.182645  0.405955    1.00
77332    57002.0  0.958079 -0.370366  ...  0.088563  0.017342   15.97
...          ...       ...       ...  ...       ...       ...     ...
279863  169142.0 -1.927883  1.125653  ...  0.292680  0.147968  390.00
280143  169347.0  1.378559  1.289381  ...  0.389152  0.186637    0.76
280149  169351.0 -0.676143  1.126366  ...  0.385107  0.194361   77.89
281144  169966.0 -3.113832  0.585864  ...  0.884876 -0.253700  245.00
281674  170348.0  1.991976  0.158476  ...  0.002988 -0.015309   42.53

[1492 rows x 30 columns]
57735     0
197206    0
148196    0
68761     0
77332     0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 1492, dtype: int64
(1492, 30) (1193, 30) (299, 30)

/usr/local/lib/python3.11/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

model evaluation

Accuracy Score

In [40]:
# accuracy on training data
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)

In [41]:
print('Accuracy on Training data : ', training_data_accuracy)

Accuracy on Training data :  0.9513830678960603

In [42]:
# accuracy on test data
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [43]:
print('Accuracy score on Test Data : ', test_data_accuracy)

Accuracy score on Test Data :  0.9498327759197325